// schemas/labPreAssessment.js
const { z } = require("zod");

const DoctorSchema = z.object({
  name: z.string(),
});

const LastEditBySchema = z.object({
  id: z.string(),
  name: z.string(),
  lastEditTime: z.string(),
});

const TestResultSchema = z.object({
  doctor: DoctorSchema,
  lastEditBy: LastEditBySchema,
  _id: z.string(),
  testId: z.string(),
  testType: z.string(),
  nameTest: z.string(),
  result: z.string(),
  suggestion: z.string(),
  registrationID: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  __v: z.number(),
});

const UpdatedBySchema = z.object({
  doctorWarehouse: z.null().or(z.any()),
  status: z.string(),
  isDelete: z.boolean(),
  NewMember: z.boolean(),
  isVerify: z.boolean(),
  statusSetup: z.string(),
  _id: z.string(),
  email: z.string(),
  password: z.string(),
  username: z.string(),
  role: z.string(),
  name: z.string(),
  uidClinic: z.string(),
  clinicId: z.string(),
  uidWarehouse: z.null().or(z.any()),
  warehouseId: z.null().or(z.any()),
  corpId: z.string(),
  accountType: z.string(),
  uidCorp: z.string(),
  employeeId: z.string(),
  uidEmployee: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  __v: z.number(),
});

const MCUAnamnesaSchema = z.object({
  womenOnly: z.array(z.any()),
  _id: z.string(),
  perceivedDisease: z.string(),
  diseaseSuffered: z.string(),
  treatmentHistory: z.string(),
  alergi: z.string(),
  diseaseFamilyHistory: z.string(),
  surgeryHistory: z.string(),
  accidentHistory: z.string(),
  sinusitis: z.string(),
  glands: z.string(),
  vision: z.string(),
  hearing: z.string(),
  asthma: z.string(),
  skin: z.string(),
  tuberculosis: z.string(),
  shortBreath: z.string(),
  coughedBlood: z.string(),
  abdominalPain: z.string(),
  stomachUlcer: z.string(),
  hepatitis: z.string(),
  gallBladder: z.string(),
  bowelHabits: z.string(),
  weightChanged: z.string(),
  varicoseVeins: z.string(),
  lumpBreast: z.string(),
  cancer: z.string(),
  heartDisease: z.string(),
  rheumatic: z.string(),
  abnormalHeartbeat: z.string(),
  highBloodPressure: z.string(),
  stroke: z.string(),
  seriousChestPain: z.string(),
  bloodDisease: z.string(),
  kidneyDisease: z.string(),
  painfulPassageUrine: z.string(),
  bloodUrine: z.string(),
  diabetes: z.string(),
  headaches: z.string(),
  dizziness: z.string(),
  epilepsy: z.string(),
  surgical: z.string(),
  accident: z.string(),
  tropicalDisease: z.string(),
  fearOfHeight: z.string(),
  mentalCondition: z.string(),
  abnormalSmear: z.string(),
  gynecological: z.string(),
  pregnant: z.string(),
  smoking: z.string(),
  amountSmoking: z.string(),
  otherSmoking: z.string(),
  coffee: z.string(),
  amountCoffee: z.string(),
  otherCoffee: z.string(),
  alcohol: z.string(),
  amountAlcohol: z.string(),
  otherAlcohol: z.string(),
  sport: z.string(),
  sportAmount: z.string(),
  registrationID: z.string(),
  updatedBy: UpdatedBySchema,
  createdAt: z.string(),
  updatedAt: z.string(),
  __v: z.number(),
});

const HazardTuvSchema = z.object({
  noise: z.string(),
  highTemperature: z.string(),
  lowTemperature: z.string(),
  routineVibrate: z.string(),
  dustOrSmoke: z.string(),
  dangerMedicine: z.string(),
  operateHardEquipment: z.string(),
  activeMedicine: z.string(),
  attentionColor: z.string(),
  onHigher: z.string(),
  staffOffice: z.string(),
  pantry: z.string(),
  noisePekerja: z.string(),
  highTempWorker: z.string(),
  lowTempWorker: z.string(),
  localVibrate: z.string(),
  fullBodyVibrate: z.string(),
  electromagnetic: z.string(),
  highAirPressure: z.string(),
  lowAirPressure: z.string(),
  ionizingRadiation: z.string(),
  nonIonizingRadiation: z.string(),
  organicDust: z.string(),
  unorganicDust: z.string(),
  heavyMetal: z.string(),
  organicSolvent: z.string(),
  irritantIngredient: z.string(),
  pesticide: z.string(),
  metalVapor: z.string(),
  bacteria: z.string(),
  bodyLiquid: z.string(),
  insect: z.string(),
  waste: z.string(),
  heavyLift: z.string(),
  repetitiveMotion: z.string(),
  unergonomicBodyPosition: z.string(),
  longTimeSitting: z.string(),
  longTimeStanding: z.string(),
  staticPosition: z.string(),
  lightingLess: z.string(),
  monitor: z.string(),
  workInHeight: z.string(),
  unsuitableWorkload: z.string(),
  unmatchSkill: z.string(),
  ambiguTask: z.string(),
  careerPath: z.string(),
  shiftWork: z.string(),
  colleagueConflict: z.string(),
  familyConflict: z.string(),
  earRinging: z.string(),
  hearingLoss: z.string(),
  tinglingHand: z.string(),
  shortnessBreath: z.string(),
  coughing: z.string(),
  behaviourChange: z.string(),
  headache: z.string(),
  skinDisease: z.string(),
  lowBackPain: z.string(),
  shoulderPain: z.string(),
  soreEye: z.string(),
  sleepDisorder: z.string(),
});

const EyeSchema = z.object({
  rightSklera: z.string(),
  rightKonjungtiva: z.string(),
  rightPupil: z.string(),
  rightLensa: z.string(),
  leftSklera: z.string(),
  leftKonjungtiva: z.string(),
  leftPupil: z.string(),
  leftLensa: z.string(),
  colorBlind: z.string(),
  rightNearVisusWithGlasses: z.string(),
  rightFarVisusWithGlasses: z.string(),
  leftNearVisusWithGlasses: z.string(),
  leftFarVisusWithGlasses: z.string(),
});

const EarSchema = z.object({
  rightEarlobe: z.string(),
  leftEarlobe: z.string(),
  rightHearingFunction: z.string(),
  leftHearingFunction: z.string(),
  rightMembranTimpani: z.string(),
  leftMembranTimpani: z.string(),
});

const NoseSchema = z.object({
  mukosa: z.string(),
  konka: z.string(),
  septum: z.string(),
});

const MouthSchema = z.object({
  tooth: z.array(z.string()),
  tongue: z.string(),
  tonsil: z.string(),
  faring: z.string(),
});

const NeckSchema = z.object({
  kelenjarLimfa: z.string(),
  kelenjarGondok: z.string(),
  kelenjarGetahBening: z.string(),
  kelenjarTiroid: z.string(),
});

const RaspiratorySchema = z.object({
  auskultasi: z.string(),
  breathingMovement: z.string(),
  inspeksi: z.string(),
  palpasi: z.string(),
  perkusi: z.string(),
});

const CardioVaskularSchema = z.object({
  vena: z.string(),
  heartSound: z.string(),
  inspeksi: z.string(),
  palpasi: z.string(),
  perkusi: z.string(),
  auskultasi: z.string(),
  otherCardioVaskular: z.string(),
});

const DigestivusSchema = z.object({
  abdomen: z.string(),
  heart: z.string(),
  limpa: z.string(),
  bowel: z.string(),
  inspeksi: z.string(),
  palpasi: z.string(),
  perkusi: z.string(),
  auskultasi: z.string(),
});

const LimbSystemSchema = z.object({
  upper: z.string(),
  bottom: z.string(),
  sensoric: z.string(),
  edema: z.string(),
  spine: z.string(),
  fisiologis: z.string(),
  patologis: z.string(),
});

const GenitourinariaSchema = z.object({
  kidney: z.string(),
  bladder: z.string(),
  anus: z.string(),
  auskultasi: z.string(),
});

const MCUPhysicalExamSchema = z.object({
  hazardTuv: HazardTuvSchema,
  eye: EyeSchema,
  ear: EarSchema,
  nose: NoseSchema,
  mouth: MouthSchema,
  neck: NeckSchema,
  raspiratory: RaspiratorySchema,
  cardioVaskular: CardioVaskularSchema,
  digestivus: DigestivusSchema,
  limbSystem: LimbSystemSchema,
  genitourinaria: GenitourinariaSchema,
  _id: z.string(),
  BMINormal: z.string(),
  hazard: z.string(),
  etcPemeriksaanFisik: z.string(),
  result: z.string(),
  suggestion: z.string(),
  registrationID: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  __v: z.number(),
});

const LabPreAssessmentDataSchema = z.object({
  isDone: z.boolean(),
  radDone: z.boolean(),
  testResult: z.array(TestResultSchema),
  _id: z.string(),
  registrationID: z.string(),
  MCUAnamnesaID: MCUAnamnesaSchema,
  MCUPhysicalExamID: MCUPhysicalExamSchema,
  __v: z.number(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const LabPreAssessmentResponseSchema = z.object({
  message: z.string(),
  status: z.boolean(),
  data: LabPreAssessmentDataSchema,
});

module.exports = {
  DoctorSchema,
  LastEditBySchema,
  TestResultSchema,
  UpdatedBySchema,
  MCUAnamnesaSchema,
  MCUPhysicalExamSchema,
  LabPreAssessmentDataSchema,
  LabPreAssessmentResponseSchema,
};
